# @package _global_
env_type: halfcheetah
env_name: halfcheetah-expert-v2

algorithm: RED
training:
  batch_size: 2048
reinforcement:
  learning_rate: 0.0003
  ppo_epochs: 20
  entropy_loss_coeff: 0.001
imitation:
  epochs: 200 #15
  learning_rate: 0.001 #0.00003
  target_hidden_size: 20
  target_depth: 4
  predictor_hidden_size: 20
  predictor_depth: 1
  entropy_loss_coeff: 0.001
  
discriminator_adam: True
sigma: 25000
